# Generated by Django 3.0.7 on 2020-07-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_auto_20200701_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
